# Generated by Django 3.0.8 on 2020-12-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
