# Generated by Django 3.0.8 on 2020-12-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20201204_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='last_visit',
        #     field=models.DateTimeField(null=True, verbose_name='最后登录时间'),
        # ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号'),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='reg_date',
        #     field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间'),
        # ),
    ]
