# Generated by Django 3.0.6 on 2020-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='信用卡名字')),
                ('expiration_time', models.DateTimeField(null=True, verbose_name='到期日期')),
                ('repayment_time', models.DateTimeField(null=True, verbose_name='还款日期')),
                ('repay_money', models.FloatField(null=True, verbose_name='还款金额')),
            ],
        ),
    ]
