# Generated by Django 3.0.8 on 2020-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('no', models.IntegerField(db_column='dno', primary_key=True, serialize=False, verbose_name='部门编号')),
                ('name', models.CharField(db_column='dname', max_length=32, verbose_name='部门名称')),
                ('location', models.CharField(db_column='dloc', max_length=32, verbose_name='部门所在地')),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
    ]
