# Generated by Django 3.0.8 on 2020-11-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('no', models.IntegerField(db_column='eno', primary_key=True, serialize=False, verbose_name='员工编号')),
                ('name', models.CharField(db_column='ename', max_length=32, verbose_name='员工姓名')),
                ('job', models.CharField(max_length=32, verbose_name='职位')),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='月薪')),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='补贴')),
                ('dept', models.ForeignKey(db_column='dno', on_delete=django.db.models.deletion.PROTECT, to='hrs.Dept', verbose_name='所在部门')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrs.Emp', verbose_name='主管编号')),
            ],
            options={
                'db_table': 'tb_emp',
            },
        ),
    ]
